### ISSUE TITLE
Don't alert on each HelloAsso error

### ISSUE THREAD

**Issue by gturri** [Zero-Waste-Paris/membership-scripts#37]
It occurs once in a while that the helloasso api fails to give a proper reply. It's usually transient and the next run usually succeeds.
In this case it's pointless to have an alert because there is nothing we can do, and because it has no impact anyway (worst thing that can occur is that it takes 1 more hour to take into account a new registration).

So it would be better to be alerted only after N such errors in a row. 

As far as implementation is concerned, an easy way to do it would be to leverage the OptionRepository and to add an "option" to count the number of successive run failed because of an HelloAsso error.

Nb: here is an example of a stacktrace that led to this error (but there are probably several possible others)

```
app.ERROR: Failed with error:Idle timeout reached for "https://api.helloasso.com/oauth2/token".. 
#0 vendor/symfony/http-client/Response/CommonResponseTrait.php(144): Symfony\Component\HttpClient\Chunk\ErrorChunk->isFirst()
#1 steparis.fr/vendor/symfony/http-client/Response/TransportResponseTrait.php(52): Symfony\Component\HttpClient\Response\CurlResponse::initialize(Object(Symfony\Component\HttpClient\Response\CurlResponse))
#2 /src/Services/HelloAssoAuthenticator.php(75): Symfony\Component\HttpClient\Response\CurlResponse->getStatusCode()
#3 /src/Services/HelloAssoAuthenticator.php(54): App\Services\HelloAssoAuthenticator->refreshTokens()
#4 /src/Services/HelloAssoAuthenticator.php(43): App\Services\HelloAssoAuthenticator->getFreshTokens() #5 steparis.fr/src/Services/HelloAssoConnector.php(79): App\Services\HelloAssoAuthenticator->getAccessToken()
#6 /src/Services/HelloAssoConnector.php(55): App\Services\HelloAssoConnector->getHelloAssoJsonSubscriptionsForOneCampaign(Object(DateTime), Object(DateTime), 'adherer-a-zero-...')
#7 steparis.fr/src/Services/HelloAssoConnector.php(38): App\Services\HelloAssoConnector->getAllHelloAssoSubscriptionsForOneCampaign(Object(DateTime), Object(DateTime), 'adherer-a-zero-...')
#8 /src/Services/MemberImporter.php(51): App\Services\HelloAssoConnector->getAllHelloAssoSubscriptions(Object(DateTime), Object(DateTime))
#9 /src/Controller/DefaultApi.php(87): App\Services\MemberImporter->run(false)
#10 steparis.fr/vendor/zero-waste-paris/membership-scripts/Controller/DefaultController.php(296): App\Controller\DefaultApi->apiTriggerImportRunGet('zwp666', false, 204, Array)
#11 /vendor/symfony/http-kernel/HttpKernel.php(181): OpenAPI\Server\Controller\DefaultController->apiTriggerImportRunGetAction(Object(Symfony\Component\HttpFoundation\Request))
#12 /vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\
Request), 1)
#13 steparis.fr/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 steparis.fr/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #15 steparis.fr/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() #16 steparis.fr/public/index.php(5): require_once('/home/clients/1...')
#17 {main} [] []
```

**Comment by gturri** [comment]
Fixed by f92c4638088919057930de22d965bdc5ca8aa7d5
